serenity.report.encoding = UTF-8
serenity.browser.width = 1280
serenity.browser.height = 800

# WebDriver configuration
webdriver.driver = chrome
chrome.switches = --start-maximized;--disable-popup-blocking

# Base URL
webdriver.base.url = https://blazedemo.com/

# Timeouts
serenity.timeout = 10000
